### ISSUE TITLE
Remove AWS / terraform testing from GitHub action (due to lack of current use)

### ISSUE THREAD

**Issue by kltm** [geneontology/go-fastapi#105]
As part of the cleaning efforts for terraform misses for #103 , we noticed that we have an instance `cicd-test-go-fast-api` running. We are not currently using the CICD effectively, so want to remove it as it keeps a machine up.

**Comment by kltm** [comment]
Likely just along the lines of the removal of `provision/github` and `.github/workflows/aws_test.yaml`.

**Comment by kltm** [comment]
Not a high priority, as the code is currently no_op, but @kltm will move ahead of the instance removal either way ($$$).

**Comment by kltm** [comment]
Instance and empty workspace with path have been removed.

**Comment by sierra-moxon** [comment]
closing as completed.
