### ISSUE TITLE
Create ansible/terraform deployment for go-fastapi

### ISSUE THREAD

**Issue by sierra-moxon** [geneontology/go-fastapi#14]

**Comment by kltm** [comment]
The step after this would be #55

**Comment by kltm** [comment]
This is currently in the stage of finding bugs or pain points in the devops by running through the docs.
Once this is complete, we will go live, but may continue exercising the docs.

**Comment by kltm** [comment]
Noting that #55 is the blocker on geneontology/amigo#696

**Comment by kltm** [comment]
This has been put to production, so closing unless problems found with #70
