### ISSUE TITLE
query GO labels in bulk 

### ISSUE THREAD

**Issue by sierra-moxon** [geneontology/go-fastapi#27]
see ticket: https://github.com/geneontology/helpdesk/discussions/430
this is already doable like this: 
http://api.geneontology.org/api/ontol/labeler/?id=GO%3A0001505&id=GO%3A0006259&id=GO%3A0006403 but a POST might be better here with long lists.

**Comment by cmungall** [comment]
Is the action here only to do this as POST or is there more work that needs done?
