### ISSUE TITLE
Fix http(s?) issue when querying the RDF endpoint after it’s migration to https

### ISSUE THREAD

**Issue by sierra-moxon** [geneontology/go-fastapi#56]
when we moved the GO infrastructure to https before Seth left, a previously working endpoint (the pathway endpoint that was working on the hand built EC2 instance and tested via Patrick’s work with the pathway widget), is now giving errors when trying to access the RDF endpoint.
I haven’t had a chance to debug further, but I’m pretty sure this is a simple config fix. The new API is http/https agnostic, this endpoint querying another backend seems to be the issue.

**Comment by sierra-moxon** [comment]
this one is fixed; currently using http for RDF endpoint, https for golr.

**Comment by kltm** [comment]
@sierra-moxon Were we going to migrate the rdf endpoint to HTTPS? As we are likely going to have to do that anyways, I'm assuming that automatic upgrade should cause any issues?
