### ISSUE TITLE
Add GitHub Actions tests for deployability of GO API

### ISSUE THREAD

**Issue by kltm** [geneontology/go-fastapi#80]
@abessiari is going to look at making sure some basic devops-related testing is enabled in GHA for code changes. This could be a jumping off point for application-based testing for the GO API (mentioned elsewhere by @sierra-moxon ).

As well, this is a trial for future devops tests for our public services.

**Comment by abessiari** [comment]
@kltm 

This automation would be implemented using github action/workflow and it would use the 
go-devops-base docker image and test the following:
- provision an instance to aws using the go-deploy (terraform +  config-instance.yaml)
- provision a go-fast-api stack using the  go-deploy tool. (ansible + config-stack.yaml)
- make some requests to go fast api and make sure it comes up
- destroy the aws instance

**Comment by kltm** [comment]
Tagging on @sierra-moxon to have it on everybody's radar.
