### ISSUE TITLE
add apache redirect to support documented API URLs

### ISSUE THREAD

**Issue by sierra-moxon** [geneontology/go-fastapi#81]
We need an Apache redirect from https://api.geneontology.org/api to https://api.geneontology.org/ to support our documented URLs here: https://geneontology.org/docs/tools-guide/

**Comment by kltm** [comment]
I'm not seeing a reason not to just update the docs at this point?
If there is some standard that we need to be hitting, I think we can just do that when we start working on the API again.

**Comment by kltm** [comment]
Cheers!
