### ISSUE TITLE
GO-CAM "search" endpoints in the GO API do not return expected results

### ISSUE THREAD

**Issue by kltm** [geneontology/go-fastapi#92]
GO-CAM "search" endpoints in the GO API do not return expected results. For example 

https://api.geneontology.org/api/users/0000-0003-1813-6857

and 

https://api.geneontology.org/api/users/0000-0003-1813-6857/models

Would be expected to return non-empty (`[]`) JSON results.

Reported by @kimrutherford

**Comment by kltm** [comment]
Before we start digging in too much @sierra-moxon @dustine32 do you have any ideas?

**Comment by kltm** [comment]
Also noting issue https://github.com/geneontology/go-fastapi/issues/87

**Comment by sierra-moxon** [comment]
I will take a look.

**Comment by sierra-moxon** [comment]
notes from debugging today:

this [part of the query](https://github.com/geneontology/go-fastapi/blob/9411c34855aa99e719870b7aaef53b8d12e40e57/app/routers/users_and_groups.py#L68):
```
            # Getting some information on the contributor
            optional { ?orcidIRI rdfs:label ?name } .
            BIND(IF(bound(?name), ?name, ?orcid) as ?name) .
            optional { ?orcidIRI vcard:organization-name ?organization } .
            optional {
                ?orcidIRI has_affiliation: ?affiliationIRI .
                ?affiliationIRI rdfs:label ?affiliation
            } .
```
seems to be preventing records from being returned.  I need to dig further as to why this restriction on the query would block the models from returning; if I exclude the affiliation, etc, I get back models.

**Comment by sierra-moxon** [comment]
talking briefly with Chris, not sure why we would need affiliation, etc in this query, so shortest path is to remove that bind stanza.

**Comment by sierra-moxon** [comment]
closing as complete; pls of course reopen if more issues arise.
