### ISSUE TITLE
"Internal Server Error" from /api/taxon/{taxon}/models

### ISSUE THREAD

**Issue by kimrutherford** [geneontology/go-fastapi#94]
Hi.

I'm getting an Internal Server Error from `/api/taxon/{taxon}/models` when looking up NCBITaxon:4896 (pombe).

I tried on the [webpage](https://api.geneontology.org) and with curl:

```sh
curl -X 'GET' \
  'https://api.geneontology.org/api/taxon/NCBITaxon%3A4896/models' \
  -H 'accept: application/json'
```

The error is returned after 60 seconds.

**Comment by sierra-moxon** [comment]
I replicated this locally today; looking into it.

**Comment by kimrutherford** [comment]
Hi.  Has there been any progress on this issue?  We'd like to use this API to update PomBase with the pombe GO-CAM details.

Thanks!

**Comment by kltm** [comment]
@kimrutherford Unfortunately, there has not been much progress here with meetings and some other things that have come up. This is still in the queue though. 

Also see https://github.com/geneontology/noctua/issues/895#issuecomment-2167022756

**Comment by kimrutherford** [comment]
Hi.  I just tried this:

```sh
curl -X 'GET' \
  'https://api.geneontology.org/api/taxon/NCBITaxon%3A4896/models' \
  -H 'accept: application/json'
```

but got "Internal Server Error" after 60 seconds.

**Comment by sierra-moxon** [comment]
Thanks for the report @kimrutherford - I still need to deploy the fix to the API server :)

**Comment by kimrutherford** [comment]
Hi @sierra-moxon

I'm still getting the "Internal Server Error".  We'd like to use this endpoint for getting GO-CAMs details for PomBase.

**Comment by kimrutherford** [comment]
Hi.

Sorry to bother you again about this.  The API was working yesterday but today it's back to giving "Internal Server Error":

```
> time curl -X 'GET' \
  'https://api.geneontology.org/api/taxon/NCBITaxon%3A4896/models' \
  -H 'accept: application/json'
```
gives:
```
Internal Server Error
real    1:01.14
user    0.021
sys     0.007
maxmem  13 MB
faults  0
```

It always takes 60 seconds to fail.

Oddly, the API calls that succeeded yesterday also took 60 seconds.

**Comment by sierra-moxon** [comment]
@kimrutherford - no bother at all - I am hacking away at getting the fixes for these deployed.  will take a look here.

**Comment by sierra-moxon** [comment]
this is now returning content: 
```
curl -X 'GET' \
  'https://api.geneontology.org/api/taxon/NCBITaxon%3A4896/models' \
  -H 'accept: application/json'
```

**Comment by kltm** [comment]
Now seems fixed.
