### ISSUE TITLE
/api/gp/{id}/models for uniprotkb accessions?

### ISSUE THREAD

**Issue by dlrice** [geneontology/go-fastapi#98]
My objective is to obtain the GO-CAM ids attached to any UniProtKB accession. I have seen the endpoint [/api/gp/{id}/models](https://api.geneontology.org/#/pathways/get_gocams_by_geneproduct_id_api_gp__id__models_get) at https://api.geneontology.org/#/ and this works fine for the example id:

## MGI:3588192
```
 curl -X 'GET' \
  'https://api.geneontology.org/api/gp/MGI:3588192/models' \
  -H 'accept: application/json'

[{"gocam":"http://model.geneontology.org/5745387b00001770","title":"Zcchc16, zinc finger, CCHC domain containing 16"},{"gocam":"http://model.geneontology.org/MGI_MGI_3588192","title":"Rtl4 (MGI:MGI:3588192)"}]
```

However, trying this with a uniprotkb accession:

## P05067
```
curl -X 'GET' \
  'https://api.geneontology.org/api/gp/P05067/models' \
  -H 'accept: application/json'
Internal Server Error
```

I see both of these IDs in https://go-public.s3.amazonaws.com/files/gocam-gps.json as gpids:
```
  {
    "gocam": "http://model.geneontology.org/SYNGO_2279",
    "gpids": [
      "http://identifiers.org/uniprot/P05067" <-------------------
    ],
    "gpnames": [
      "APP",
      "A4_HUMAN"
    ]
  },
...
  {
    "gocam": "http://model.geneontology.org/MGI_MGI_3588192",
    "gpids": [
      "http://identifiers.org/mgi/MGI:3588192" <-------------------
    ],
    "gpnames": [
      "Rtl4",
      "Zcchc16 Mmus"
    ]
  },
```

I'm not sure if I'm doing something wrong which causes the internal server error or if a bug is causing this?

**Comment by kltm** [comment]
@dlrice To start digging into this, I would note that the correct formation would be:
`curl -X 'GET' 'https://api.geneontology.org/api/gp/UniProtKB:P05067/models' -H 'accept: application/json'`
The namespace is required for queries as, technically, internal IDs are ambiguous. (MGI, as they have an historical "double namespacing", have special mechanisms to allow resolution.)

I'll make a ticker for the internal server error.

I believe, there may be an additional wrinkle in the expectations of what the GO API returns here. Maybe @sierra-moxon or @dustine32 could check or expand on this before I start digging in, but I'm not sure these calls return all models without exception, but may be filtering to a certain quality level, as not all models are useful for display, but only serve as a background to produce "standard annotation".

**Comment by dustine32** [comment]
@kltm Looking [here](https://github.com/geneontology/go-fastapi/blob/ee56256459e2279592d5031378ae62a489a75486/app/routers/pathway_widget.py#L64-L69) at the code, the default (without supplying the `causalmf` param) behavior is to return any model where the GP ID is the object of an "enabled by" edge.

If the `causalmf` param is used, the filter for models of "at least two consecutive causal relation edges" connected to the query GP would be applied.

**Comment by kltm** [comment]
@dustine32 Ah, hm. That's going to the SPARQL endpoint--not what I was expecting.
Looking at our endpoint (`sparql.geneontology.org`) with that query, it also returns nothing, so at least that's consistent (although the model itself looks like it should connect?).

I guess the next question would be: since the file `gocam-gps.json` is coming from `api-gorest-2021`, using `/models/gp`, via `AllModelsGPs`, why the functional difference in output? The queries seem a little different, but the latter looks more restrictive...

**Comment by dustine32** [comment]
@kltm It is another "http" vs "https" mismatch for UniProtKB IDs.

For `UniProtKB:P05067` the full class URI in the models is `http://identifiers.org/uniprot/P05067` but the API code expands UniProtKB into `https://identifiers.org/uniprot` by using [go-site/metadata/db-xrefs.yaml](https://github.com/geneontology/go-site/blob/feeac4959065e2b868147108fdc6cd0c55e4b3f9/metadata/db-xrefs.yaml#L2762) via `prefixmaps` as @sierra-moxon kindly explains in [this ticket](https://github.com/geneontology/go-site/issues/2000).

**Comment by balhoff** [comment]
This pull request seems to address this, and has been open for a while: https://github.com/geneontology/go-site/pull/2176

**Comment by kltm** [comment]
@balhoff @dustine32 , okay, how does this propagate into the API once the PR has been merged?

**Comment by dustine32** [comment]
@kltm From what I gather it is more involved than initially suspected. The API uses [prefixmaps](https://github.com/linkml/prefixmaps/tree/main) to load contexts and it seems that the prefixes are frozen with each release version.

To update, there are some instructions [here](https://github.com/linkml/prefixmaps/blob/main/README.md#refreshing-the-data) but it may be faster to have @sierra-moxon or @cmungall do this for us?

**Comment by kltm** [comment]
@dustine32 I figured it was something like this :) I'll add this to the agenda for tomorrow.

**Comment by kltm** [comment]
@sierra-moxon to look into this and grab the latest.

**Comment by kltm** [comment]
@dlrice We are currently maybe looking at next week or so, but don't have an exact timeline. There are a few things we need to wrap up on other fronts before we are able to get this out.

**Comment by dlrice** [comment]
Purely for my planning as we have marked integration of https://github.com/geneontology/wc-gocam-viz/ into uniprot.org entry pages as a milestone and this issue blocks that - is it possible to get a very rough estimate of when this will likely be resolved?

**Comment by sierra-moxon** [comment]
@dlrice - can you try an API call like this: 
```curl -X 'GET' 'https://api.geneontology.org/api/gp/UniProtKB:P05067/models' -H 'accept: application/json'```

if you use:
```curl -X 'GET' 'https://api.geneontology.org/api/gp/P05067/models' -H 'accept: application/json' ``` 

you should now get a somewhat more helpful error message than "internal server error":
 ```{"message":"Value error occurred: Invalid CURIE format"}```

**Comment by dlrice** [comment]
> can you try an API call like this: `curl -X 'GET' 'https://api.geneontology.org/api/gp/UniProtKB:P05067/models' -H 'accept: application/json'`

Works!

> if you use: `curl -X 'GET' 'https://api.geneontology.org/api/gp/P05067/models' -H 'accept: application/json'` you should now get a somewhat more helpful error message than "internal server error": `{"message":"Value error occurred: Invalid CURIE format"}`

Yes seeing this.

Closing the issue now. Thanks!
