### ISSUE TITLE
In some cases, the GO API returns a "server error", instead of gracefully failing

### ISSUE THREAD

**Issue by kltm** [geneontology/go-fastapi#99]
A minor issue, but it was discovered that the call `https://api.geneontology.org/api/gp/P05067/models` returned a server error, instead of a error code and/or message.

In general, it would be good to catch exceptions like this and return some kind of error message/code.

From #98

**Comment by sierra-moxon** [comment]
now returns: "{"message":"Value error occurred: Invalid CURIE format"}" 
ready to close?

**Comment by kltm** [comment]
Now seems fixed.
